In [1]:
#shift + enter to run lines

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
#shift tabs gives you instructions in jupyter

In [9]:
np.arange(0,10,2) #range and stepsize 

array([0, 2, 4, 6, 8])

In [10]:
#now we create a twodimensional or threedimensional array 

In [11]:
np.zeros(shape=(10,5)) #rows and columns of zero created as floats

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape=(2,4)) #rows -height of array and columns - width of array - of 1 floats values

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#array of random numbers 

In [13]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [14]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [15]:
arr2 = np.random.randint(0,100,10)

In [16]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [17]:
#now we find the max and min values of an array

In [18]:
arr.max()

95

In [19]:
arr.argmax() #find location

0

In [20]:
arr.min()

9

In [23]:
arr.argmin() #find location

7

In [24]:
arr.mean()

60.8

In [26]:
arr.reshape((2,5)) #you can reshape according to the number of elements that are present in your array

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [27]:
#now lets explore indexing

In [28]:
mat = np.arange(0,100).reshape(10,10)

In [29]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
mat.shape #check the shape of your array

(10, 10)

In [33]:
row = 0
col = 1

mat[row,col]

1

In [34]:
mat [4,6]

46

In [35]:
mat[:,1] #now we grab all values of a column

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [36]:
mat[2,:] #now we grab all values of a column

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
mat[0:3,0:3] #now slicing a portion of the matrix 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [39]:
mynewmat = mat.copy()

In [40]:
mynewmat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
#now we convert valus for a portion of our array

In [41]:
mynewmat[0:6,:] = 999

In [42]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])